// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfzfuivyxkfkwhhgapko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmemZ1aXZ5eGtma3doaGdhcGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDU5MTEsImV4cCI6MjA3NDQ4MTkxMX0.LfEd30p2NS1M9YQt-KpNLgvvbyVGTwfMfhwfu6Q97sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});